name = "TTT Userconfig"
author = "TacticalTrainingTeam"
prefix = "ttt_userconfig"
mainprefix = "z"

[version]
path = "addons/main/script_version.hpp"
git_hash = 0

[files]
include = [
    "mod.cpp",
    "meta.cpp",
    "logo_ttt_userconfig.png",
    "logo_ttt_userconfig_ca.paa",
    "LICENSE.md",
    "README.md",
]
exclude = []

[properties]
author = "TacticalTrainingTeam"
